import { ExtensionResponse } from "../src/lib/responses";

/**
 * A map of results generated by a Testing Lambda using the Client.
 */
export interface TestResponses {
  /**
   * Whether the assertions succeeded or failed.
   */
  result: "success" | "failure";
  /**
   * The test responses.
   */
  responses: Record<string, TestResponse>;
}

/**
 * A test result for a single request.
 */
export interface TestResponse {
  /**
   * A description of the test case.
   */
  description: string;
  /**
   * The value returned from the Client.
   */
  value:
    | string
    | Array<string>
    | { type: "Buffer"; data: Array<number> }
    | Buffer
    | null;
  /**
   * The raw Extension response.
   */
  response: ExtensionResponse;
}

/**
 * A single Extension ARN in the aws-layer-arns output.
 */
export interface ExtensionArn {
  layerArn: string;
  account: string;
  region: string;
  architecture: string;
  version: number;
}
