# Post-release Publish package to npm
name: Publish to npm

on:
  release:
    types: [published]
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: npm
  cancel-in-progress: true

jobs:
  publish-npm:
    name: Publish to npm
    environment: stable
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3 # https://github.com/actions/checkout
      - name: Setup
        uses: actions/setup-node@v3 # https://github.com/actions/setup-node
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
          cache: npm
      - run: npm ci
      - run: npm run build
      - run: npm test
      - name: Prepare dist
        run: |
          npx tsc --project tsconfig.dist.json
          cp README.md CHANGELOG.md LICENSE ./dist
          jq 'del(.devDependencies) | del(.scripts)' package.json > ./dist/package.json
      - name: Publish
        run: cd dist && npm publish --dry-run
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }} 
