name: Release Please!

on:
  push:
    branches: [main]

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please!
        uses: googleapis/release-please-action@v5 # https://github.com/googleapis/release-please-action
        with:
          # https://github.com/googleapis/release-please-action#basic-configuration
          release-type: node
          token: ${{ secrets.GH_PAT_ACTIONS_WORKFLOW }} # PAT required to trigger downstream workflows
