name: Release Please!

on:
  push:
    branches: [main]

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please!
        uses: google-github-actions/release-please-action@v3 # https://github.com/google-github-actions/release-please-action
        with:
          # https://github.com/google-github-actions/release-please-action#configuration
          release-type: node
          package-name: lambda-params-secrets
          token: ${{ secrets.GH_PAT_ACTIONS_WORKFLOW }} # PAT required to trigger downstream workflows
          bump-minor-pre-major: true
